<link rel="stylesheet" href="../css/ourServices.css">
<section>
    <div class="row">
    <div class="column">
        <div class="card">
        <h3 style="color:black">What is Everybody Welcome?</h3>
        <p>
            Everybody Welcome is a straightforward, smart tool to help you record, share and market relevant
            accessibility information about your venue.
        </p>
        </div>
    </div>
    <div class="column">
        <div class="card">
            <h3 style="color:black">How much does it cost? </h3>
            <p>
            Everybody Welcome is free to use and includes listing in the Directory for one year. At the end of each year,
    you will be prompted to check the accuracy of your listing before it renews, giving you the opportunity to
    make changes and giving visitors confidence that the information provided is current, relevant and
    accurate.
    For those who want to take their accessibility to the next level, our Access Tracker tool is available at just
    £XXXX per year.
            </p>
        </div>
    </div>
    <div class="column">
        <div class="card">
        <h3 style="color:black">What do I need to do?</h3>
        <p>
        Simply answer a short series of questions about your business, venue or service, add some images and in
just a few clicks you have a handy, accurate accessibility summary that you can share on your website, in
your social media or anywhere else that takes your fancy!
        </p>
        </div>
    </div>
    <div class="column">
        <div class="card">
        <h3 style="color:black">What do I get?</h3>
        <p>
        Not only does creating an Everybody Welcome listing give you a unique URL to share with your target
audiences, it also generates an exclusive QR code to display around your venue, enabling you to provide
access information for your visitors when and where they need it.
Your Everybody Welcome listing also links back to your own website, ensuring that visitors who need
additional information know exactly where to find it.
Each listing is included in our free to use directory which enables potential visitors to search for venues by
location, type or accessibility features, leading to better experiences for visitors and increased footfall and
revenue for you.
If you want to dig a little deeper, our Access Tracker self-audit tool will enable to you to audit the
accessibility of your offering in moore detail, providing information and tools to support you in creating an
action plan for improvement.
        </p>
        </div>
    </div>
    <div class="column">
        <div class="card">
            <h3 style="color:black">Why is it needed?</h3>
            <p>
            Research shows that more than half of disabled people are not confident about visiting new places and that
    79% have had a disappointing trip or had to change their plans at the last minute due to poor accessibility.
    77% also find that accessibility information hard to find or inaccurate.* (*Source: Euan's Guide Access Survey 2019)
    Venues, on the other hand, are unsure what information provide or find existing methods of providing
    access information costly, complicated or time-consuming so often provide nothing.
    As a result, people with additional access needs are missing out on visits and experiences and businesses
    are missing out on the additional income that would be generated by those visits.
    Everybody Welcome is designed to change that by supporting businesses to provide relevant accessibility
    information easily and quickly and enabling consumers to plan visits with ease.
            </p>
        </div>
    </div>
    <div class="column">
        <div class="card">
        <h3 style="color:black">What are the other advantages?</h3>
        <p>
        Destinations are now recognising the value of the Purple Pound: the spending power of disabled people,
which is worth over £274billion in the U.K. alone. Creating Everybody Welcome guides within a given
destination starts to improve the accessibility of the destination as a whole, increasing visitor numbers,
enhancing revenue and improving visitor experiences.
The U.K. government too has recognised the opportunity for growth that this sector has. In fact, the 2021
Tourism Recovery Plan aims for the U.K. to be THE most accessible tourism destination in Europe by 2025
and to increase the number of disabled visitors from Europe by one third by this time. Providing accurate
accessibility information is key to achieving this goal and is exactly what Everybody Welcome achieves.
        </p>
        </div>
    </div>
    </div>
</section>